# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be495d582c6615167e161767bc3ee9e87f67c18c1ad561efff86a69fd7d6b6b2c98aa7bf00655aeb9e14778ce638c650eb5cdc5d761a4570a30ed9f95e56f81d

test:
  secret_key_base: b273fc17abc0de545e3f5095b8734780ebc57928b4bf3a785f0357074847492bc658cf5c2c62b78b0f0668dde671dc77884651dece64273605291eb7bdda6aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
